package com.algorithm.justworks;

import java.time.Duration;
import java.util.Optional;

import com.algorithm.justworks.InMemoryDB;
import com.algorithm.justworks.InMemoryDBImpl;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.MethodOrderer;
import org.junit.jupiter.api.Order;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestMethodOrder;

/**
 * The test class below can be considered as a playground - feel free to modify it as you need, e.g.:
 * - add your own custom tests
 * - delete existing tests
 * - modify test contents or expected output
 *
 * The results of tests from this file will always be at the beginning of the report generated by clicking the "Run" button.
 *
 * The results of these tests do not affect the final score (unless the project fails to build).
 */
@TestMethodOrder(MethodOrderer.OrderAnnotation.class)
public class SandboxTests {
    private InMemoryDB db;

    @BeforeEach
    void setUp() {
        db = new InMemoryDBImpl();
    }

    @Test
    @Order(1)
    void testSample() {
        Assertions.assertTimeoutPreemptively(Duration.ofMillis(200), () -> {
            Assertions.assertEquals(Optional.of(5), db.setOrInc("A", "B", 5));
            Assertions.assertEquals(Optional.of(11), db.setOrInc("A", "B", 6));
            Assertions.assertEquals(Optional.of(11), db.get("A", "B"));
            Assertions.assertTrue(db.get("A", "C").isEmpty());
            Assertions.assertTrue(db.delete("A", "B"));
            Assertions.assertFalse(db.delete("A", "C"));
        });
    }
}
